---
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group created using cloudformation

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
      KeyName: abc
      SecurityGroups:
        - !Ref SecurityGroup

  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating S3 bucket using cloudformation
    Properties:
      BucketName: my-bucket2-using-cf